---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: check-prereqs
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-check-prereqs
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
rules:
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclass
  verbs: ["get", "list", "watch"]
- apiGroups: ["maistra.io"]
  resources:
  - servicemeshcontrolplanes
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-check-prereqs
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-check-prereqs
subjects:
- kind: ServiceAccount
  name: check-prereqs
  namespace: {{ default "default" .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: check-prereqs
  annotations:
    argocd.argoproj.io/sync-wave: "-900"
spec:
  template:
    spec:
      containers:
        - name: check
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              set -x

              # Wait storage class
              while : ; do
                if oc get sc -o "jsonpath={.items[*].metadata.annotations['storageclass\.kubernetes\.io/is-default-class']}" | grep -q ^true$; then
                  echo "INFO: Default storage class available."
                  break
                fi
                echo "INFO: Default storage class not available, waiting."
                sleep 10
              done

              # Wait service mesh control plane
              while : ; do
                if oc get servicemeshcontrolplane -n istio-system -ojsonpath={.items[*].status.conditions[*].type} | grep -q Ready; then
                  echo "INFO: Service mesh control plane available."
                  break
                fi
                echo "INFO: Service mesh control plane not available, waiting."
                sleep 10
              done
      restartPolicy: Never
      serviceAccountName: check-prereqs
  backoffLimit: 10
