{{- if .Values.humio.enabled }}
---
apiVersion: aiops.ibm.com/v1alpha1
kind: HumioConnection
metadata:
  name: humio-sample
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  # Add fields here
  filters: "kubernetes.namespace_name=robot-shop"
{{- end }}
{{- if .Values.kafka.enabled }}
---
apiVersion: aiops.ibm.com/v1alpha1
kind: KafkaConnection
metadata:
  name: kafka-sample
  annotations:
    argocd.argoproj.io/sync-wave: "100"
# spec:
  # Add fields here
{{- end }}
{{- if .Values.kube.enabled }}
---
apiVersion: aiops.ibm.com/v1alpha1
kind: KubeConnection
metadata:
  name: kube-sample
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  # Add fields here
  appNamespace: "robot-shop"
{{- end }}
