---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  finalizers:
    - argoproj.io/finalizer
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  resourceCustomizations: |
    ceph.rook.io/CephCluster:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.state == "Created" and obj.status.phase == "Ready" then
            hs.status = "Healthy"
          end
          if obj.status.message ~= nil then
            hs.message = obj.status.message
          end
        end
        return hs
    ceph.rook.io/CephFilesystem:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.phase == "Ready" then
            hs.status = "Healthy"
            hs.message = obj.status.phase
          end
        end
        return hs
