apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentbit
  namespace: {{ default "default" .Release.Namespace }}
  labels:
    k8s-app: {{ .Release.Name }}
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
{{- if .Values.es.autodiscovery }}
      initContainers:
        - name: wait-for-humio
          image: {{ default "humio/strix" .Values.strixImage }}
          imagePullPolicy: {{ default "Always" .Values.strixImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Ready"
          - "pod/{{ .Release.Name }}-humio-core-0"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
  {{- if .Values.global -}}
    {{- if .Values.global.sharedTokens }}
      {{- if .Values.global.sharedTokens.fluentbit }}
        - name: wait-for-shared-tokens
          image: {{ default "humio/strix" .Values.strixImage }}
          imagePullPolicy: {{ default "Always" .Values.strixImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Complete"
          - "job/{{ .Release.Name }}-create-shared-tokens"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
      {{- end -}}
    {{- end -}}
  {{- end  }}
{{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ default "fluent/fluent-bit:1.2.2" .Values.image }}
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-H"]
        livenessProbe:
          httpGet:
            path: /api/v1/metrics
            port: 2020
        imagePullPolicy: {{ default "Always" .Values.imagePullPolicy }}
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          {{- if .Values.es.autodiscovery }}
          value: "{{ .Release.Name }}-humio-core-es.{{ .Release.Namespace }}"
          {{- else }}
          value: {{ default "cloud.humio.com" .Values.humioHostname | quote }}
          {{- end }}
        - name: FLUENT_ELASTICSEARCH_PORT
          value: {{ default "9200" .Values.es.port | quote }}
        - name: FLUENT_ELASTICSEARCH_TLS
          {{- if .Values.es.tls }}
          value: "On"
          {{- else }}
          value: "Off"
          {{- end }}
        - name: FLUENT_ELASTICSEARCH_TLS_VERIFY
          {{- if and .Values.es.tls .Values.es.tls_verify }}
          value: "On"
          {{- else }}
          value: "Off"
          {{- end }}
        - name: HUMIO_REPO_NAME
          value: {{ .Values.humioRepoName | quote }}
        {{- if .Values.token }}
        - name: HUMIO_INGEST_TOKEN
          valueFrom:
            secretKeyRef:
              name: fluentbit-custom-token
              key: token
        {{- else -}}
          {{- if .Values.global -}}
            {{- if .Values.global.sharedTokens }}
              {{- if .Values.global.sharedTokens.fluentbit }}
        - name: HUMIO_INGEST_TOKEN
          valueFrom:
            secretKeyRef:
              name: fluentbit-shared-token
              key: token
              {{- end -}}
            {{- end -}}
          {{- end -}}
        {{- end  }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: {{ .Release.Name }}-fluent-bit-config
      serviceAccountName: {{ .Release.Name }}-fluentbit-read
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
