apiVersion: v1
kind: Service
metadata:
  name: {{ include "humio-core.fullname" . }}-http
  labels:
    app: {{ template "humio-core.name" . }}
    chart: {{ template "humio-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "humio-core.name" . }}
    release: {{ .Release.Name }}
