humio-core:
  enabled: false
  
humio-strix:
  enabled: false
  replicas: 10
  imagePullPolicy: Always
  simulationOptions:
    hecSimulation:
      users: 5

humio-fluentbit:
  enabled: true
  # Replace this token value with Ingest token from "robot-shop" repo after Humio and Fluentbit deployed in the environment.
  # create the repo "robot-shop" and replace this "dummy_token" with ingestion token of "robot-shop" repo.
  token: "dummy_token"
  # humioRepoName: aiops
  humioRepoName: "robot-shop"
  humioReleaseName: "humio"
  humioNamespace: "humio-logging"
  es:
    tls: false # TLS On. Set to false to turn it off.
    tls_verify: false # TLS verify On. Set to false to turn it off.
    autodiscovery: true
  securityContext:
    privileged: true
  scc:
    enabled: true
  inputConfig: |-
    [INPUT]
        Name             tail
        Path             /var/log/containers/*bookinfo_*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    256MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/log/containers/*robot-shop_*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    256MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/log/containers/*qotd*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    256MB
        Skip_Long_Lines  On
  resources:
    limits:
      cpu: 256m
      memory: 500Mi
    requests:
      cpu: 128m
      memory: 256Mi

humio-metrics:
  enabled: false
