---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: hostpathRequiresPrivileged
          value: "true"
        - name: image.tag
          value: "v1.7.8"
    repoURL: https://charts.rook.io/release/
    chart: rook-ceph
    targetRevision: v1.7.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
