---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/huang-cn/sample-app-gitops
    path: gitops-charts/rook-ceph-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: ceph.rook.io
      jsonPointers:
        - /spec/disruptionManagement/managePodBudgets
      kind: CephCluster
