---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-shop
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: robot-shop
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: openshift
          value: "true"
        - name: ocCreateRoute
          value: "true"
        - name: nodeport
          value: "true"
    path: K8s/helm
    repoURL: https://github.com/instana/robot-shop/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
