---
{{- if or .Values.sample.quickburn.medium .Values.sample.quickburn.large }}
{{- $productGroupId := toString .Values.sample.credentials.productGroupId -}}
apiVersion: v1
kind: Secret
metadata:
  name: fyre-{{ .Values.sample.credentials.user }}-secret
  namespace: {{ default "default" .Release.Namespace }}
data:
  username: "{{ b64enc .Values.sample.credentials.user }}"
  password: "{{ b64enc .Values.sample.credentials.token }}"
  product_group_id: "{{ b64enc $productGroupId }}"
type: Opaque
{{- end }}
