---
{{- $product_group_id := toString .Values.fyre.credential.product_group_id -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "default" .Release.Namespace }}-fyre-secret
  namespace: {{ default "default" .Release.Namespace }}
data:
  password: "{{ b64enc .Values.fyre.credential.password }}"
  product_group_id: "{{ b64enc $product_group_id }}"
  username: "{{ b64enc .Values.fyre.credential.username }}"
type: Opaque
