apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-argocd-admin-ai
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "010"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-argocd-admin-ai-istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "010"
subjects:
  - kind: ServiceAccount
    name: openshift-argocd-admin-ai
    namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
