apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jaeger-operator.v1.25.0
