apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-post-install
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
   - secrets
  verbs: ["get", "list", "create"]
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - routes
  verbs: ["get", "list", "watch"]
