apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-post-install-update-ingest-token"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-post-install
      initContainers:
        - name: wait-for-humio
          image: "{{ default "humio/strix" .Values.strixImage }}"
          imagePullPolicy: {{ .Values.strixImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Ready"
          - "pod/{{ .Release.Name }}-humio-core-0"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
        - name: wait-for-shared-tokens
          image: {{ default "humio/strix" .Values.strixImage }}
          imagePullPolicy: {{ default "Always" .Values.strixImagePullPolicy }}
          command:
          - kubectl
          - wait
          - "--for=condition=Complete"
          - "job/{{ .Release.Name }}-create-shared-tokens"
          - "-n"
          - {{ .Release.Namespace }}
          - "--timeout=1500s"
      containers:
        - name: fluentbit-update-token
          image: "docker.io/thinkonce/humioctl-update-token:latest"
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          command: ["/fluentbit-update-ingest-token.sh"]
          env:
            - name: RELEASE_NAME
              value: "{{ .Release.Name }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
          - name: data
            mountPath: /opt/humio
      volumes:
      - name: data
        emptyDir: {}