{{- if .Values.hecToken }}
apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-custom-hec-token
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  {{ .Values.hecTokenSecretKeyName }}: {{ .Values.hecToken | b64enc | quote }}
{{- end }}
