---
apiVersion: batch/v1
kind: Job
metadata:
  name: humio-image-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |

              image_pull_secret=$(oc get secret ibm-entitlement-key -n {{.Values.humio_namespace}} -o jsonpath={.metadata.name})

              if [[ "${image_pull_secret}" != ibm-entitlement-key ]]; then
                  oc create secret docker-registry ibm-entitlement-key \
                  --docker-username={{.Values.dockerUsername}} \
                  --docker-password={{.Values.dockerPassword}} \
                  --docker-server=index.docker.io \
                  --namespace={{.Values.humio_namespace}}
                  oc secrets link serviceaccount/default ibm-entitlement-key \
                  --for=pull -n {{.Values.humio_namespace}}
              fi

      restartPolicy: Never
      serviceAccountName: argocd-manager
  backoffLimit: 4
